name: Frontend build
on: [push]

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out this code
        uses: actions/checkout@v3

      - name: Cache node modules
        id: cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: modules-${{ hashFiles('package-lock.json') }}

      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "npm"

      - name: Install deps
        # https://www.jonathan-wilkinson.com/github-actions-cache-everything
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          # @todo fix this legacy peer deps issue if we can
          npm install --legacy-peer-deps

      - name: Lint
        run: |
          npm install -g css-checker-kit
          npm install -g jscpd
          bash scripts/lint.sh

      - name: Build frontend
        run: |
          npm run build:ssr
          npm run test

      - name: Test frontend
        run: |
          npm run test
